default: &default_settings
  socket: /tmp/mysql.sock
  adapter: mysql2
  encoding: utf8
  charset: utf8
  collation: utf8_general_ci
  pool: 5
  username: root
  password: 

development:
  <<: *default_settings
  database: copycopter_development

test:
  <<: *default_settings
  database: copycopter_test